### ISSUE TITLE
unnormalized_bases error in load_data function

### ISSUE THREAD

**Issue by pavitramohanty** [llSourcell/ethereum_future#11]
Traceback (most recent call last):   File "C:\Users\Admin\Desktop\btcpy.py", line 328, in <module>     X_train, Y_train, X_test, Y_test, Y_daybefore, unnormalized_bases, window_size = load_data("bitcoinprices.csv", 50)   File "C:\Users\Admin\Desktop\btcpy.py", line 67, in load_data     unnormalized_bases = d0[start:end,0:1,21] IndexError: index 21 is out of bounds for axis 2 with size 2

This error i got when i run the program nd is unable to solve the error so help me with this

**Comment by yuval-mntr** [comment]
As I understand, 21 is the index of the target column is Siraj's dataset. try use your len(df.columns) -1 assuming your dataframe most right column is the target/label
